Repository Nomas-X/AET_AUX, pull requests merged in 2024-11, with the labels that each got.

#35 Nomas dev
  .hemtt/missions/testMission.Altis/cba_settings.sqf
  LICENSE
  addons/common/data/master_cba_settings.sqf
  addons/common/functions/ai/fn_disableLayerAI.sqf
  addons/common/functions/ai/fn_enableLayerAI.sqf
  addons/discord_rich_presence/Licenses/DiscordRichPresence.txt
  addons/discord_rich_presence/Licenses/discord-rpc-csharp.txt
  addons/friendly_fire_notifications/LICENSE
  addons/main/script_version.hpp
  addons/user_input_menus/LICENSE
  addons/vehicle_unflipping/LICENSE
Labels: documentation, enhancement

#34 reviewed
  addons/common/CfgFunctions.hpp
  addons/common/functions/ai/fn_disableLayerAI.sqf
  addons/common/functions/ai/fn_enableLayerAI.sqf
  addons/common/functions/utility/fn_getLayer.sqf
  addons/common/functions/utility/fn_markTriggersInLayer.sqf
  addons/common/functions/utility/fn_markTriggersInMission.sqf
  addons/common/functions/utility/fn_triggerToMarker.sqf
  addons/disclaimer/functions/fn_handleSafety.sqf
  addons/disclaimer/functions/fn_play.sqf
  addons/plan_importer/functions/fn_addActions.sqf
  addons/plan_importer/functions/fn_createMarkers.sqf
  addons/plan_importer/functions/fn_deletePlan.sqf
  addons/plan_importer/functions/fn_importPlan.sqf
  addons/plan_importer/functions/fn_showActionsCondition.sqf
Labels: enhancement

#36 Nomas dev
  .hemtt/missions/testMission.Altis/mission.sqm
  addons/common/functions/utility/fn_markTriggersInLayer.sqf
  addons/common/functions/utility/fn_markTriggersInMission.sqf
  addons/common/functions/utility/fn_triggerToMarker.sqf
  addons/disclaimer/functions/fn_play.sqf
  addons/main/script_version.hpp
  addons/plan_importer/CfgFunctions.hpp
  addons/plan_importer/XEH/XEH_preInit.sqf
  addons/plan_importer/functions/fn_addActions.sqf
  addons/plan_importer/functions/fn_deletePlan.sqf
  addons/plan_importer/functions/fn_importPlan.sqf
  addons/plan_importer/functions/fn_postInit.sqf
  addons/plan_importer/functions/fn_removeActions.sqf
  addons/plan_importer/functions/fn_showActionsCondition.sqf
Labels: bug, enhancement
